In [1]:
from utils.create_split_masks import create_split_masks, create_split_masks_regression
import torch 
import numpy as np
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

***

## Classification

In [2]:
from utils.GNN_model import ImprovedGNN, ResidualGCN, GraphAttentionNet, ResidualGraphSAGE
from utils.evaluate_gnn_model import evaluate_gnn_model

In [3]:
def model_data_judged(model_type, data, check):
    data_classification = torch.load(f"data/{data}.pt", weights_only=False)
    model = model_type(list(data_classification.x[0].shape)[0], 64, len(data_classification.y.unique()))

    train_mask_classification, val_mask_rclassification, test_mask_classification = create_split_masks(data_classification)
    data_classification.test_mask = test_mask_classification

    model_classification = model
    model_classification.load_state_dict(torch.load(f'check/{check}.pt', map_location='cpu'))  # or 'cuda'
    model_classification.eval()  
    result_GNN = evaluate_gnn_model(data_classification, model_classification, mask_type='test')

    return result_GNN

In [4]:
_ = model_data_judged(ImprovedGNN, "data_quantile_Target_QC_aggcat", "enhanced_improved_gnn_data_quantile_Target_QC_aggcat")

Accuracy: 0.684977184977185
Classification Report:
               precision    recall  f1-score   support

           0     0.8998    0.7673    0.8282     40076
           1     0.5221    0.4832    0.5019     16618
           2     0.0339    0.8811    0.0653       286

    accuracy                         0.6850     56980
   macro avg     0.4853    0.7105    0.4652     56980
weighted avg     0.7853    0.6850    0.7292     56980

Confusion Matrix:
 [[30749  7317  2010]
 [ 3423  8029  5166]
 [    3    31   252]]
